include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_use_package_imports
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - only_throw_errors
    - prefer_final_in_for_each
    - prefer_single_quotes
    - require_trailing_commas

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.gen.dart
    - test/**/*.mocks.dart
  errors:
    invalid_annotation_target: ignore
    always_use_package_imports: error
    avoid_print: error
    cascade_invocations: ignore
    flutter_style_todos: ignore
  language:
    strict-casts: true
    strict-raw-types: true
